Ext.define('bentonMobile.store.Topics', {
    extend: 'Ext.data.Store',
    requires: ['bentonMobile.model.Topics'],
    config: {
        model: 'bentonMobile.model.Topics',
        data: [
        {"term":"All","tid":0},
        {"term":"70\/70","tid":"93","parentTid":"8"},
        {"term":"A La Carte","tid":"89","parentTid":"8"},
        {"term":"Accessibility for the Disabled","tid":"36"},
        {"term":"Advertising","tid":"68"},
        {"term":"Agenda","tid":"11"},
        {"term":"Auctions","tid":"27","parentTid":"26"},
        {"term":"Broadcasting","tid":"14"},
        {"term":"Cable","tid":"8"},
        {"term":"Censorship","tid":"6134","parentTid":"35"},
        {"term":"Children and Media","tid":"28"},
        {"term":"Civic Engagement","tid":"6136","parentTid":"35"},
        {"term":"Community Media","tid":"48"},
        {"term":"Court case","tid":"90"},
        {"term":"Cyberwarfare and Cybersecurity","tid":"1193"},
        {"term":"Digital Content","tid":"20"},
        {"term":"Digital Divide","tid":"34"},
        {"term":"Diversity","tid":"46"},
        {"term":"Education technology","tid":"55"},
        {"term":"Election 2008","tid":"843","parentTid":"67"},
        {"term":"Election 2012","tid":"8740","parentTid":"67"},
        {"term":"Elections and Media","tid":"67"},
        {"term":"Electronic Health Records","tid":"6142","parentTid":"6141"},
        {"term":"Emergency Communications","tid":"7"},
        {"term":"Energy and Climate","tid":"2634"},
        {"term":"FCC Reform","tid":"95"},
        {"term":"Gender","tid":"1364","parentTid":"46"},
        {"term":"Gov performance","tid":"6138","parentTid":"35"},
        {"term":"Government &amp; Communications","tid":"35"},
        {"term":"Health and Media","tid":"70"},
        {"term":"Health Information Technology","tid":"6141","parentTid":"70"},
        {"term":"Impact of various media on health","tid":"6145","parentTid":"70"},
        {"term":"Indecency Regulation","tid":"23"},
        {"term":"Interactive","tid":"3989","parentTid":"68"},
        {"term":"Interactivity","tid":"1277","parentTid":"14"},
        {"term":"Internet","tid":"87","parentTid":"64"},
        {"term":"Internet","tid":"1361","parentTid":"19"},
        {"term":"Internet\/Broadband","tid":"15"},
        {"term":"Journalism","tid":"24"},
        {"term":"Labor","tid":"53"},
        {"term":"Lobbying","tid":"6137","parentTid":"35"},
        {"term":"Localism","tid":"47"},
        {"term":"Low Power Radio","tid":"32","parentTid":"14"},
        {"term":"Low-income","tid":"1363","parentTid":"46"},
        {"term":"Media Coverage of Health Issues","tid":"6144","parentTid":"70"},
        {"term":"Media Ownership","tid":"21"},
        {"term":"Mobile DTV","tid":"4960","parentTid":"14"},
        {"term":"Multicasting","tid":"58","parentTid":"14"},
        {"term":"Municipal Networks","tid":"29","parentTid":"15"},
        {"term":"Must-carry","tid":"42","parentTid":"8"},
        {"term":"National Privacy Plan","tid":"5927","parentTid":"1518"},
        {"term":"Network management","tid":"2123","parentTid":"15"},
        {"term":"Network management","tid":"2124","parentTid":"19"},
        {"term":"Network Neutrality","tid":"57","parentTid":"15"},
        {"term":"Online privacy","tid":"1518","parentTid":"15"},
        {"term":"Open government","tid":"6135","parentTid":"35"},
        {"term":"PEG","tid":"88","parentTid":"8"},
        {"term":"Policymakers","tid":"51"},
        {"term":"Private equity","tid":"86","parentTid":"21"},
        {"term":"Product Placement","tid":"1391","parentTid":"68"},
        {"term":"Public Broadcasting","tid":"22","parentTid":"14"},
        {"term":"Public Interest Obligations","tid":"30","parentTid":"14"},
        {"term":"Quotes","tid":"71"},{"term":"Radio","tid":"16","parentTid":"14"},
        {"term":"Radio","tid":"79","parentTid":"64"},
        {"term":"Regulatory classification","tid":"5417","parentTid":"15"},
        {"term":"Report on past event","tid":"6133","parentTid":"11"},
        {"term":"Research","tid":"37"},
        {"term":"Retransmission consent","tid":"4987","parentTid":"14"},
        {"term":"Satellite","tid":"64"},
        {"term":"Search Neutrality","tid":"5930","parentTid":"20"},
        {"term":"Secondary market","tid":"1259","parentTid":"26"},
        {"term":"Seniors","tid":"1362","parentTid":"46"},
        {"term":"Spectrum","tid":"26"},
        {"term":"Stories from Abroad","tid":"4504"},
        {"term":"Telecommunication","tid":"9"},
        {"term":"Telehealth","tid":"6143","parentTid":"6141"},
        {"term":"Television","tid":"12","parentTid":"14"},
        {"term":"Ten Years Ago","tid":"69"},
        {"term":"Texting","tid":"1360","parentTid":"19"},
        {"term":"TPRC","tid":"45","parentTid":"37"},
        {"term":"TV","tid":"78","parentTid":"64"},
        {"term":"TV","tid":"85","parentTid":"9"},
        {"term":"TV via cell phone","tid":"2038","parentTid":"19"},
        {"term":"Universal Broadband","tid":"82","parentTid":"15"},
        {"term":"Universal Service","tid":"25","parentTid":"9"},
        {"term":"Universal Service Modernization","tid":"41","parentTid":"31"},
        {"term":"Unlicensed","tid":"56","parentTid":"26"},
        {"term":"Upcoming event","tid":"6131","parentTid":"11"},
        {"term":"Upcoming policy issue","tid":"6132","parentTid":"11"},
        {"term":"Violence Regulation","tid":"84"},
            {"term":"What News Was","tid":"76"},
            {"term":"Wireless Telecommunications","tid":"19"},
        ],
        listeners: {
            load: function(store, records, successful, op, e) {
                //console.log(store);
            }
        }
    }
});